AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndOfLine:
  Enabled: False

Layout/LineLength:
  AllowURI: true
  Enabled: false

Metrics/BlockLength:  
  IgnoredMethods: 
    - 'describe'
    - 'context'
    - 'it'