name: Build and Test

on:
  workflow_dispatch:
  push: 
    branches: 
      - main
  pull_request: 
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.7' ]

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and Test
        run: |
          gem install bundler:2.2.32
          bundle install
          bundle exec rspec